version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    # Error handling
    - errcheck
    - staticcheck
    - ineffassign
    - unused

    # Complexity
    - gocyclo
    - bodyclose

linters-settings:
  goimports:
    local-prefixes: github.com/zenkiet/zen-attendance-server
  gofumpt:
    extra-rules: true
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: package-comments
        disabled: false